disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Portfolio"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # description = "Short site description goes here"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "Daniel Kroner Nielsen"
  email = "you@example.com"
  image = "images/profile/profile-placeholder.svg"
  imageQuality = 96
  headline = "Gigachad vibecoder B-)"
  bio = "Your short bio goes here"
  links = [
    { linkedin = "https://linkedin.com/in/your-profile" }
  ]
